// Filename-only elimination — cheap first pass before we even fetch descriptions.
export const NON_PHOTO_FILENAME_PATTERNS = [
  "flag", "coat_of_arms", "coa_", "locator", "map", "icon", "logo",
  "emblem", "seal_of", "location_", "orthographic", "symbol", "chart",
  "graph", "diagram",
];

// Description-based rejection — these topics show up constantly
export const NEGATIVE_KEYWORDS = [
  "election", "vote", "voting", "voter", "president", "prime minister", "parliament",
  "protest", "demonstration", "rally", "military", "army", "soldier", "war", "battle",
  "ceremony", "summit", "conference", "meeting", "food", "dish", "cuisine", "meal",
  "restaurant", "currency", "banknote", "coin", "stamp", "passport", "logo", "chart", "graph",
  "population pyramid", "portrait", "official photo", "airport", "celebrity", "politician",
  "crowd", "artist", "musician", "singer", "actor", "actress", "dancer", "model", "fashion",
  "writer", "poet", "author", "composer", "director", "producer", "athlete", "governor",
  "mayor", "minister", "ambassador", "diplomat", "judge", "lawyer", "statue", "sculpture",
  "monument", "memorial", "cargo", "container", "industrial", "factory", "facility",
  "close-up", "macro", "zoom", "sign", "plaque", "inscription", "text", "interior", "inside",
  "room", "ceiling", "child", "children", "national food", "traditional food",
  "cultural food", "mall", "shopping center", "container ship", "cruise ship", "ferry",
  "submarine", "airplane", "helicopter", "train", "bus", "car", "bicycle", "motorcycle",
  "scooter", "truck", "van", "bridge construction", "road construction",
  "building construction", "skyscraper construction", "demolition", "fire", "flood",
  "earthquake", "tsunami", "document", "treaty", "constitution", "signature", "charter",
  "manifesto", "coat of arms", "seal", "infobox", "diagram", "table", "timeline",
  "statistics", "museum exhibit", "artifact", "artefact", "pottery", "ceramics", "painting",
  "mural", "tapestry", "manuscript", "exhibition", "showcase", "gallery interior",
  "press conference", "speech", "podium", "audience", "classroom", "student", "lecture",
  "university campus building", "headquarters", "embassy building", "courtroom",
  "parliamentary", "politicians", "state visit", "handshake", "construction site", "crane",
  "power plant", "refinery", "highway", "freeway", "motorway", "traffic jam", "parking lot",
  "subway station", "railway track", "dump", "landfill", "pollution", "smog", "sewage",
  "headshot", "selfie", "group photo", "pose", "posing", "family photo",
  "commercial advertisement", "billboard", "poster", "flyer", "brochure",
  "commercial premises", "storefront", "shop window", "shopping mall", "supermarket",
  "office building", "industrial complex", "warehouse", "factory interior", "laboratory",
  "research facility", "data center", "server room", "control room", "command center",
  "operations center", "emergency response center", "fire station", "police station",
  "hospital", "clinic", "medical center", "pharmacy", "laboratory equipment", "observatory",
  "telescope", "satellite dish", "antenna", "communication tower", "cruise terminal",
  "ferry terminal", "bus station", "train station", "airport terminal", "hangar", "runway",
  "taxiway", "control tower", "boarding gate", "check-in counter", "security checkpoint",
  "customs area", "baggage claim", "concourse", "lounge", "ballot box", "voting booth",
  "polling station", "election office", "campaign poster", "political rally", "protest march",
  "strike", "sit-in", "occupation", "civil unrest", "riot", "clash", "confrontation",
  "arrest", "detention", "police line", "manifestation", "voting station", "referendum",
  "plebiscite", "census", "survey", "polling data", "people", "person", "individual", "group",
  "family", "adult", "elderly", "teenager", "tent", "camp", "shelter", "refugee camp",
  "displaced persons camp", "internally displaced persons camp", "drawing", "sketch",
  "illustration", "cartoon", "comic strip", "animation", "video game screenshot",
  "historical event", "black and white photo", "sepia photo", "vintage photo",
  "archival photo", "nationwide protests", "marching", "demonstrating", "activism",
  "civil rights", "human rights", "social movement", "political campaign",
  "election campaign", "referendum campaign", "public demonstration", "street protest",
  "food festival", "cultural festival", "music festival", "art festival", "film festival",
  "literary festival", "sports event", "athletic competition", "marathon", "race",
  "tournament", "hockey match", "soccer match", "football match", "basketball game",
  "baseball game", "tennis match", "golf tournament", "swimming competition",
  "track and field event", "gymnastics competition", "olympic games", "paralympic games",
  "world cup", "championship", "league match", "friendly match", "exhibition match",
  "concert", "live performance", "theater play", "opera performance", "ballet performance",
  "dance recital", "performance", "vacation", "holiday", "travel", "tourism", "sightseeing",
  "excursion", "trip", "journey", "adventure", "expedition", "singing", "dancing", "acting",
  "performing", "rehearsal", "audition", "casting", "production", "filming", "shooting",
  "biography", "autobiography", "memoir", "diary", "journal", "letter", "correspondence",
  "speech transcript", "interview transcript", "right to vote", "voter registration",
  "election results", "ballot counting", "vote tallying", "election monitoring",
  "women's suffrage", "buildings", "architecture", "urban planning", "city planning",
  "landscape architecture", "garden design", "interior design", "singer-songwriter", "band",
  "orchestra", "choir", "ensemble", "soloist", "conductor", "arranger", "political leader",
  "government official", "vase", "vessel", "urn", "antique", "relic", "art piece", "carving",
  "artifact display", "museum piece", "ceramic vase", "decorative object", "cruise liner",
  "ocean liner", "docked ship", "fishing boats", "shipyard", "seaport", "cargo port",
  "container terminal", "port of", "vessels docked", "ships in port", "dockyard",
  "loading dock", "girl", "boy", "kid", "kids", "baby", "infant", "toddler",
  "man with a child", "father and daughter", "mother and child", "family portrait",
  "holding a child", "posing with", "smiling at camera", "close-up portrait", "elderly woman",
  "young man", "young woman", "gastronomy", "culinary", "delicacy", "recipe", "street food",
  "food market", "buffet", "platter", "plate of", "serving of", "national dish",
  "typical dish", "local dish", "regional dish", "slum", "shanty", "shantytown", "poverty",
  "destroyed", "debris", "rubble", "ruined building", "collapsed building",
  "damaged building", "informal settlement", "refugee", "makeshift", "tin roof",
  "corrugated roof", "dilapidated", "abandoned building", "war-torn", "conflict zone",
  "disaster zone", "aftermath", "wreckage", "shacks", "squalor", "scorpion", "spider",
  "insect", "arachnid", "bug", "hockey", "stadium", "arena", "ice rink", "sports complex",
  "sports facility", "gymnasium", "locker room", "training facility", "sports venue",
  "collage", "montage", "composite image", "grid of images",
];

// Description-based boost — the words a real landscape/city photo caption
// tends to contain.
export const POSITIVE_KEYWORDS = [
  "skyline", "aerial", "panorama", "landscape", "view of", "cityscape", "downtown",
  "mountain", "beach", "coast", "coastline", "lake", "valley", "desert", "waterfall",
  "street", "landmark", "temple", "cathedral", "castle", "bridge", "harbor", "harbour",
  "port", "countryside", "village", "national park", "island", "river", "forest",
  "nature reserve", "mountain range", "provincial park", "state park", "cliffs", "bay",
  "archipelago", "church", "mosque", "palace", "fortress", "plaza", "square", "fountain",
  "garden", "park", "waterfront", "boardwalk", "promenade", "pier", "marina", "lighthouse",
  "canyon", "gorge", "plateau", "volcano", "glacier", "fjord", "delta", "cave", "cavern",
  "spring", "geyser", "hot spring", "lagoon", "reef", "bayou", "swamp", "wetland", "savanna",
  "prairie", "steppe", "tundra", "fireworks", "street market", "harvest", "vineyard",
  "winery", "orchard", "tea plantation", "coffee plantation", "rice terrace", "bamboo forest",
  "cherry blossom", "autumn foliage", "coral reef", "atoll", "oasis", "dune", "sand dunes",
  "cliffs of", "cape", "peninsula", "valley view", "highlands", "woodland", "rainforest",
  "cloud forest", "jungle", "wildlife sanctuary", "shrine", "pagoda", "monastery", "abbey",
  "basilica", "synagogue", "ruins", "ancient ruins", "archaeological site", "amphitheater",
  "aqueduct", "windmill", "monolithic", "citadel", "clock tower", "obelisk", "pavilion",
  "old town", "historic district", "colonial architecture", "colorful houses", "canals",
  "gondola", "street scene", "marketplace", "bazaar", "souk", "amusement park",
  "botanical garden", "national monument landscape", "bird's-eye view", "wide-angle",
  "scenic outlook", "spectacular view", "vibrant", "picturesque", "reflection on water",
  "dusk", "dawn", "historic center", "scenic view",
];